"""Ajout colonne hashed_password à User

Revision ID: 376f1600a405
Revises: 55bcc971a9f8
Create Date: 2025-05-20 11:36:11.328037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376f1600a405'
down_revision = '55bcc971a9f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.String(length=128), nullable=False))
        batch_op.drop_column('pwd_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pwd_hash', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('hashed_password')

    # ### end Alembic commands ###
